name: Build Portable EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout del código
        uses: [actions/checkout](https://github.com)@v4

      - name: Configurar Node.js
        uses: [actions/setup-node](https://github.com)@v4
        with:
          node-version: 18
          # HEMOS QUITADO LA LÍNEA DEL CACHE PARA EVITAR EL ERROR

      - name: Instalar dependencias
        run: npm install

      - name: Empaquetar Aplicación
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Subir ejecutable a GitHub
        uses: [actions/upload-artifact](https://github.com)@v4
        with:
          name: Ejecutable-Portable-Windows
          path: dist/*.exe
          if-no-files-found: error
